import Head from 'next/head'
import Image from 'next/image'
import Posts from '../components/posts/Posts'

export default function Home({posts}) {
  return (
    <div>
      <Head>
        <title>Content Manager Website</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.ico" />
      </Head>
      <main>
        {posts && posts.map((post) => (
          <Posts key={post.post_id} post={post} />
        ))}
        
      </main>

      
    </div>
  )
}

export async function getStaticProps() {
  const response = await fetch('http://127.0.0.1:8000/posts/')
  const posts = await response.json();

  return {
    props: {
      posts,
    }
  }
}
