# Generated by Django 4.2.2 on 2023-06-26 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
